from distutils.core import setup

# see requirements.txt for dependencies

setup(
    name = "assetgentags",
    version = "0.1.dev01",
    author = "Seyi Ogunyemi",
    author_email = "me@micrypt.com",
    description = "A set of simple tags for including assets generated by assetgen",
    long_description = open("README.rst").read(),
    license = "BSD",
    url = "http://github.com/micrypt/django-assetgentags",
    packages = [
        "assetgentags",
        "assetgentags.templatetags",
    ],
    classifiers = [
        "Development Status :: 3 - Alpha",
        "Environment :: Web Environment",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: BSD License",
        "Operating System :: OS Independent",
        "Programming Language :: Python",
        "Framework :: Django",
    ]
)
